# Generated by Django 4.2.30 on 2026-08-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category_name',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(default='Beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=10),
        ),
    ]
